import 'dart:math' as math;

import 'package:everslot_recurrence/src/engine/occurrence.dart';
import 'package:everslot_recurrence/src/engine/recurrence_engine.dart';
import 'package:everslot_recurrence/src/rule/recurrence_anchor.dart';
import 'package:everslot_recurrence/src/rule/recurrence_rule.dart';
import 'package:everslot_recurrence/src/time/local_date_time.dart';
import 'package:meta/meta.dart';

/// A stored per-occurrence change (moved, cancelled or edited occurrence).
@immutable
final class OccurrenceOverride<T> {
  const new(this.key, {this.cancelled = false, this.newStartLocal, this.newDurationMinutes, this.payload});

  /// Original occurrence key (identity; never changes when moved).
  final String key;

  /// The occurrence is removed.
  final bool cancelled;

  /// New wall-clock start (same zone as the series), when moved.
  final LocalDateTime? newStartLocal;

  /// New duration, when edited.
  final int? newDurationMinutes;

  /// Caller data (e.g. the stored occurrence row).
  final T? payload;

  @override
  bool operator ==(Object other) =>
      other is OccurrenceOverride<T> &&
      other.key == key &&
      other.cancelled == cancelled &&
      other.newStartLocal == newStartLocal &&
      other.newDurationMinutes == newDurationMinutes &&
      other.payload == payload;

  @override
  int get hashCode => Object.hash(key, cancelled, newStartLocal, newDurationMinutes, payload);

  @override
  String toString() =>
      'OccurrenceOverride($key${cancelled ? ', cancelled' : ''}'
      '${newStartLocal == null ? '' : ', → $newStartLocal'}'
      '${newDurationMinutes == null ? '' : ', ${newDurationMinutes}min'})';
}

/// An occurrence after applying its override: original identity, effective times.
@immutable
final class MergedOccurrence<T> {
  const new({
    required this.original,
    required this.startLocal,
    required this.startUtc,
    required this.endUtc,
    required this.durationMinutes,
    this.appliedOverride,
  });

  /// The occurrence as generated by the rule.
  final Occurrence original;

  /// Effective wall-clock start.
  final LocalDateTime startLocal;

  /// Effective start instant.
  final DateTime startUtc;

  /// Effective end instant.
  final DateTime endUtc;

  /// Effective duration.
  final int durationMinutes;

  /// The applied override, if any.
  final OccurrenceOverride<T>? appliedOverride;

  /// Identity key (the original key, even when moved).
  String get key => original.key;

  bool get isAllDay => original.isAllDay;

  /// Whether the start differs from the generated one.
  bool get isMoved => startLocal != original.startLocal;

  /// Whether an override was applied.
  bool get hasOverride => appliedOverride != null;

  /// The override's payload.
  T? get payload => appliedOverride?.payload;

  @override
  bool operator ==(Object other) =>
      other is MergedOccurrence<T> &&
      other.original == original &&
      other.startLocal == startLocal &&
      other.startUtc == startUtc &&
      other.endUtc == endUtc &&
      other.durationMinutes == durationMinutes &&
      other.appliedOverride == appliedOverride;

  @override
  int get hashCode => Object.hash(original, startLocal, startUtc, endUtc, durationMinutes, appliedOverride);

  @override
  String toString() => 'MergedOccurrence($key → $startLocal${appliedOverride == null ? '' : ', overridden'})';
}

/// Merges engine output with stored per-occurrence overrides (T2.1.10).
///
/// Occurrences moved *into* the range from outside are included, occurrences
/// moved *out* are dropped, cancelled ones are removed, and edited durations
/// apply to that occurrence only. Callers pass the overrides whose original
/// key or new start falls near the range (± the longest duration); overrides
/// whose key is not an occurrence of the series are ignored as stale.
final class OverrideMerger {
  const new(this.engine);

  final RecurrenceEngine engine;

  /// Resolved occurrences overlapping `[fromLocal, toLocal)` (evaluation-zone
  /// wall clock), sorted by effective start then key.
  List<MergedOccurrence<T>> merge<T>(
    RecurrenceRule rule,
    RecurrenceAnchor anchor,
    LocalDateTime fromLocal,
    LocalDateTime toLocal,
    Iterable<OccurrenceOverride<T>> overrides, {
    String? evalZone,
    int? durationMinutes,
  }) {
    final duration = durationMinutes ?? anchor.effectiveDurationMinutes;
    final byKey = {for (final o in overrides) o.key: o};
    final longest = byKey.values.fold(duration, (m, o) => math.max(m, o.newDurationMinutes ?? 0));
    final viewZone = engine.viewZoneFor(anchor, evalZone);
    final fromUtc = engine.resolver.resolve(fromLocal, viewZone).utc;
    final toUtc = engine.resolver.resolve(toLocal, viewZone).utc;

    bool overlaps(Occurrence effective, int minutes) {
      if (anchor.allDay) {
        final start = effective.startLocal.date.atStartOfDay;
        final days = math.max(1, (minutes + 1439) ~/ 1440);
        return start.isBefore(toLocal) && start.plusDays(days).isAfter(fromLocal);
      }
      if (!effective.startUtc.isBefore(toUtc)) return false;
      return minutes == 0 ? !effective.startUtc.isBefore(fromUtc) : effective.endUtc.isAfter(fromUtc);
    }

    final result = <MergedOccurrence<T>>[];
    void addMerged(Occurrence original, OccurrenceOverride<T>? override) {
      if (override != null && override.cancelled) return;
      final minutes = override?.newDurationMinutes ?? duration;
      final start = override?.newStartLocal ?? original.startLocal;
      final effective = engine.occurrenceAt(
        anchor,
        start,
        evalZone: evalZone,
        durationMinutes: minutes,
        key: original.key,
      );
      if (!overlaps(effective, minutes)) return;
      result.add(
        MergedOccurrence<T>(
          original: engine.occurrenceAt(
            anchor,
            original.startLocal,
            evalZone: evalZone,
            durationMinutes: duration,
            key: original.key,
          ),
          startLocal: start,
          startUtc: effective.startUtc,
          endUtc: effective.endUtc,
          durationMinutes: minutes,
          appliedOverride: override,
        ),
      );
    }

    final seen = <String>{};
    for (final occurrence in engine.between(
      rule,
      anchor,
      fromLocal,
      toLocal,
      evalZone: evalZone,
      durationMinutes: longest,
    )) {
      seen.add(occurrence.key);
      addMerged(occurrence, byKey[occurrence.key]);
    }
    for (final override in byKey.values) {
      if (seen.contains(override.key) || override.cancelled) continue;
      if (override.newStartLocal == null && override.newDurationMinutes == null) continue;
      final original = engine.occurrenceForKey(rule, anchor, override.key, evalZone: evalZone);
      if (original != null) addMerged(original, override);
    }
    result.sort((a, b) {
      final c = a.startUtc.compareTo(b.startUtc);
      return c != 0 ? c : a.key.compareTo(b.key);
    });
    return result;
  }
}
