import 'package:everslot_recurrence/src/engine/recurrence_engine.dart';
import 'package:everslot_recurrence/src/rule/recurrence_anchor.dart';
import 'package:everslot_recurrence/src/rule/recurrence_rule.dart';
import 'package:everslot_recurrence/src/rule/rule_enums.dart';
import 'package:everslot_recurrence/src/rule/rule_validator.dart';
import 'package:everslot_recurrence/src/time/local_date.dart';
import 'package:everslot_recurrence/src/time/local_date_time.dart';
import 'package:meta/meta.dart';

/// Result of a "this and following" split.
@immutable
final class SeriesSplit {
  const new({required this.truncatedRule, required this.newRule, required this.newAnchor});

  /// The old series, ending just before the split; null when nothing remains
  /// before the split (the caller replaces the whole series).
  final RecurrenceRule? truncatedRule;

  /// The new series, starting at the split occurrence.
  final RecurrenceRule newRule;

  /// Anchor of the new series (the split occurrence's original start).
  final RecurrenceAnchor newAnchor;

  @override
  String toString() => 'SeriesSplit(old: $truncatedRule, new: $newRule @ $newAnchor)';
}

/// Splits a fixed series at an occurrence (T2.1.11).
///
/// The old series ends just before the split: `until` becomes the previous
/// rule occurrence (count-based series get the number of occurrences before
/// the split instead). The new series starts at the split occurrence with the
/// remaining count. Exdates/rdates are partitioned; a month day the rule
/// derived from the old anchor is made explicit when the new anchor would
/// change it (clamped months). With an unchanged new rule, the union of both
/// series equals the original series.
final class SeriesSplitter {
  const new(this.engine);

  final RecurrenceEngine engine;

  /// Splits [rule] (anchored at [anchor]) at the occurrence [splitKey].
  ///
  /// Throws [ArgumentError] when the rule isn't a fixed rule or when
  /// [splitKey] is not generated by the rule.
  SeriesSplit split(RecurrenceRule rule, RecurrenceAnchor anchor, String splitKey) {
    if (rule.type != RuleType.fixed) {
      throw ArgumentError.value(rule, 'rule', 'only fixed rules can be split');
    }
    final plan = engine.planFor(rule, anchor);
    final local = anchor.allDay ? LocalDate.tryParse(splitKey)?.atStartOfDay : LocalDateTime.tryParse(splitKey);
    if (local == null) {
      throw ArgumentError.value(splitKey, 'splitKey', 'not an occurrence key');
    }
    final split = local.epochMinute;
    if (plan.ruleMinutes(split, split).isEmpty) {
      throw ArgumentError.value(splitKey, 'splitKey', 'not generated by the rule');
    }

    var before = 0;
    int? previous;
    for (final minute in plan.ruleMinutes(plan.anchorMinute, split - 1)) {
      before++;
      previous = minute;
    }

    bool isBefore(String value) {
      final parsed = parseRuleDate(value);
      if (parsed == null) return true;
      final minute = parsed.dateTime?.epochMinute ?? parsed.date.epochDay * 1440;
      return minute < split;
    }

    bool touchesSplitDay(String value) {
      final parsed = parseRuleDate(value);
      return parsed != null && (parsed.dateTime == null || anchor.allDay) && parsed.date == local.date;
    }

    final oldExdates = [
      for (final e in rule.exdates)
        if (isBefore(e) || touchesSplitDay(e)) e,
    ];
    final newExdates = [
      for (final e in rule.exdates)
        if (!isBefore(e) || touchesSplitDay(e)) e,
    ];
    final oldRdates = [
      for (final r in rule.rdates)
        if (isBefore(r)) r,
    ];
    final newRdates = [
      for (final r in rule.rdates)
        if (!isBefore(r)) r,
    ];

    final count = rule.countMode == CountMode.occurrences ? rule.count : null;
    RecurrenceRule? truncated;
    if (count != null && before > 0) {
      truncated = rule.copyWith(count: before, exdates: oldExdates, rdates: oldRdates);
    } else if (previous != null || oldRdates.isNotEmpty) {
      // Without earlier rule occurrences, `until` just before the split makes
      // the rule generate nothing and keeps the earlier rdates.
      truncated = rule.copyWith(
        count: null,
        until: previous == null ? local.plusMinutes(-1) : LocalDateTime.fromEpochMinute(previous),
        exdates: oldExdates,
        rdates: oldRdates,
      );
    }

    var newRule = rule.copyWith(
      count: count == null ? rule.count : count - before,
      exdates: newExdates,
      rdates: newRdates,
    );
    newRule = _materializeDefaults(newRule, anchor, local);
    return SeriesSplit(
      truncatedRule: truncated,
      newRule: newRule,
      newAnchor: anchor.copyWith(start: local),
    );
  }

  /// Makes anchor-derived month days explicit when the new anchor differs.
  ///
  /// The split key is generated by the rule, so its weekday (weekly rules) and
  /// time of day (anchor-derived times) always equal the old anchor's; only a
  /// clamped month day (`monthDayOverflow: clamp`) can differ.
  static RecurrenceRule _materializeDefaults(RecurrenceRule rule, RecurrenceAnchor oldAnchor, LocalDateTime newStart) {
    final old = oldAnchor.start;
    final noDaySpec =
        rule.byWeekNo.isEmpty && rule.byYearDay.isEmpty && rule.byMonthDay.isEmpty && rule.byWeekday == null;
    if (!noDaySpec || newStart.day == old.day) return rule;
    return switch (rule.freq) {
      Frequency.monthly => rule.copyWith(byMonthDay: [old.day]),
      Frequency.yearly => rule.copyWith(
        byMonth: rule.byMonth.isEmpty ? [old.month] : rule.byMonth,
        byMonthDay: [old.day],
      ),
      _ => rule,
    };
  }
}
