import 'package:everslot/firebase/firebase_options_dev.dart' as dev;
import 'package:everslot/firebase/firebase_options_prod.dart' as prod;
import 'package:firebase_core/firebase_core.dart';

/// Firebase options of the running flavor (T1.2.13). `lib/firebase/firebase_options_<flavor>.dart`
/// are generated by `flutterfire configure` (docs/guide.md › Firebase); until then they hold
/// placeholders and Firebase stays off — no push, no Crashlytics; local reminders keep working.
/// The flavor is the compile-time `FLAVOR` define (`env/<flavor>.json`), so the FCM background
/// isolate resolves the same project.
abstract final class AppFirebaseOptions {
  static const flavor = String.fromEnvironment('FLAVOR', defaultValue: 'dev');

  static FirebaseOptions get currentPlatform =>
      flavor == 'prod' ? prod.DefaultFirebaseOptions.currentPlatform : dev.DefaultFirebaseOptions.currentPlatform;

  /// False while the generated file still holds placeholders (or on an unsupported platform).
  static bool get isConfigured {
    try {
      return !currentPlatform.projectId.startsWith('YOUR_');
    } on Object {
      return false;
    }
  }
}
